{{- if .Values.deployments.csApp.configuration.chart.auth.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.deployments.csApp.configuration.chart.auth.secret.name }}
  namespace: {{ .Values.Block.InstanceId }}
type: Opaque
stringData:
  # modify the templating info
{{- end }}
