apiVersion: v1
kind: Service
metadata:
  name: opencraft-server-headless-service
  labels:
    app: opencraft-server
spec:
  ports:
    - port: 7979
      protocol: UDP
      name: game-state
  clusterIP: None
  selector:
    app: opencraft-server
---
apiVersion: v1
kind: Service
metadata:
  name: opencraft-server-nodeport-service
spec:
  type: NodePort # Exposes the service externally via a port on each node
  selector:
    app: opencraft-server
  ports:
    - port: 7979 # Port on the service within the cluster
      targetPort: 7979 # Port on the container within the pod
      nodePort: 37979 # NodePort that will be exposed externally (range 30000-32767)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opencraft-server
spec:
  selector:
    matchLabels:
      app: opencraft-server # has to match .spec.template.metadata.labels
  serviceName: "opencraft-server"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: opencraft-server # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: opencraft
          image: jdonkervliet/opencraft-server-go:latest
          # command: ["/opencraft2/opencraft2.x86_64"]
          # args:
          #   - "-playType"
          #   - "Server"
          #   - "-serverUrl"
          #   - "0.0.0.0"
          #   - "-nographics"
          #   - "-batchmode"
          #   - "-logFile"
          #   - "/opencraft2/logs/opencraft2_server_log.txt"
          #   - "-profiler-enable"
          #   - "-logStats"
          #   - "-statsFile"
          #   - "/opencraft2/logs/opencraft2_server_stats.csv"
          #   - "-statsHttpUrl"
          #   - "http://localhost:8080/telegraf"
          ports:
            - containerPort: 7979
              name: game-state
              protocol: UDP
          volumeMounts:
            - mountPath: /opencraft/logs
              name: logs-volume
        - name: telegraf
          image: jdonkervliet/telegraf-python
          ports:
            - containerPort: 8080
              name: telegraf-http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/telegraf
              name: telegraf-sidecar-config-volume
            - mountPath: /opencraft2/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log/opencraft
            type: DirectoryOrCreate
        - name: telegraf-sidecar-config-volume
          configMap:
            name: telegraf-sidecar-config
