apiVersion: v1
kind: Service
metadata:
  name: opencraft-render-nodeport-service
spec:
  type: NodePort # Exposes the service externally via a port on each node
  selector:
    app: opencraft-render
  ports:
    - name: http-control-server
      port: 7980
      targetPort: 7980
      nodePort: 30980
    - name: signaling-server
      port: 7981
      targetPort: 7981
      nodePort: 30981
    - name: coturn-listener
      port: 3478
      targetPort: 3478
      nodePort: 30982
    - name: stream
      port: 30983
      targetPort: 30983
      nodePort: 30983
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opencraft-render
spec:
  selector:
    matchLabels:
      app: opencraft-render # has to match .spec.template.metadata.labels
  serviceName: "opencraft-render"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: opencraft-render # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: opencraft-render
          image: jdonkervliet/opencraft-client-unity:latest
          args:
            - "-logfile"
            - "/opencraft/logs/render.log"
          ports:
            - name: control-server
              containerPort: 7980
              protocol: TCP
            - name: signal-server
              containerPort: 7981
              protocol: TCP
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,video,graphics" # Add the graphics capability here
            - name: DISPLAY
              value: ":0"
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
          volumeMounts:
            - mountPath: /tmp/.X11-unix
              name: unix-display
            - mountPath: /opencraft/logs
              name: logs-volume
          securityContext:
            privileged: true
        - name: turn-server
          image: coturn/coturn
          args:
            - "-n" # no config file, use these parameters
            - "--no-cli"
            - "--min-port"
            - "30983"
            - "--max-port"
            - "30983"
            - "--log-file=stdout"
            - "-v" # verbose
            - "-z" # allow anonymous
            - "--allow-loopback-peers" # not good for security
            - "--no-multicast-peers"
          env:
            - name: DETECT_EXTERNAL_IP
              value: "yes"
            - name: DETECT_RELAY_IP
              value: "yes"
          ports:
            - containerPort: 3478
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 5349
              protocol: TCP
            - containerPort: 5349
              protocol: UDP
            - name: stream
              containerPort: 30983
              protocol: TCP
            - containerPort: 30983
              protocol: UDP
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: unix-display
          hostPath:
            path: /tmp/.X11-unix
        - name: logs-volume
          hostPath:
            path: /logs
            type: DirectoryOrCreate
