apiVersion: batch/v1
kind: Job
metadata:
  name: opencraft-client
  labels:
    app.kubernetes.io/name: opencraft-client
spec:
  template:
    spec:
      containers:
        - name: opencraft-client
          image: jdonkervliet/opencraft:v0.0.7
          command: ["/opencraft2/opencraft2.x86_64"]
          args:
            - "-playType"
            - "SimulatedClient"
            - "-serverUrl"
            - "opencraft-server-0.opencraft-server"
            - "-nographics"
            - "-batchmode"
            - "-logFile"
            - "/opencraft2/logs/opencraft2_client_log.txt" # FIXME this will go wrong when running more than 1 client
            - "-profiler-enable"
            - "-logStats"
            - "-statsFile"
            - "/opencraft2/logs/opencraft2_client_stats.csv"
            - "-statsHttpUrl"
            - "http://localhost:8080/telegraf"
          volumeMounts:
            - mountPath: /opencraft2/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log/opencraft
            type: DirectoryOrCreate
      restartPolicy: Never
