apiVersion: v1
kind: Service
metadata:
  name: opencraft-render-nodeport-service
spec:
  type: NodePort # Exposes the service externally via a port on each node
  selector:
    app: opencraft-render
  ports:
    - name: http-control-server
      port: 7980
      targetPort: 7980
      nodePort: 30980
    - name: signaling-server
      port: 7981
      targetPort: 7981
      nodePort: 30981
    - name: coturn-listener
      port: 3478
      targetPort: 3478
      nodePort: 30982
    - name: stream
      port: 7983
      targetPort: 7983
      nodePort: 30983
---
apiVersion: batch/v1
kind: Job
metadata:
  name: opencraft-render
  labels:
    app.kubernetes.io/name: opencraft-render
spec:
  template:
    spec:
      containers:
        - name: opencraft-render
          image: jdonkervliet/opencraft-client-unity:latest
          args:
            - "-logfile"
            - "/opencraft/logs/render.log"
          ports:
            - name: control-server
              containerPort: 7980
              protocol: TCP
            - name: signal-server
              containerPort: 7981
              protocol: TCP
          volumeMounts:
            - mountPath: /opencraft/logs
              name: logs-volume
        - name: turn-server
          image: coturn/coturn
          args:
            - "--min-port"
            - "30983"
            - "--max-port"
            - "30983"
          ports:
            - containerPort: 3478
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 5349
              protocol: TCP
            - containerPort: 5349
              protocol: UDP
            - name: stream
              containerPort: 30983
              protocol: TCP
            - containerPort: 30983
              protocol: UDP
      volumes:
        - name: logs-volume
          hostPath:
            path: /logs
            type: DirectoryOrCreate
      restartPolicy: Never
