{{- with .Values.image.privateRepo }}
{{- if and .enabled .generateSecret }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "k6-job.name" $ }}-registry-key
  labels:
    {{- include "k6-job.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "k6-job.imagePullSecret" $ }}
{{- end }}
{{- end }}
