apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stress-ng-web.fullname" . }} 
  labels:
    {{- include "stress-ng-web.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "jobs/*").AsConfig | nindent 2}}
