apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stress-ng-web.fullname" . }}
  labels:
    {{- include "stress-ng-web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "stress-ng-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stress-ng-web.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.privateRepo }}
      {{- if and .enabled .generateSecret }}
      imagePullSecrets:
        - name: {{ include "stress-ng-web.name" $ }}-registry-key
      {{- else if .enabled }}
      {{ $secret := .imagePullSecrets | required ".Values.image.privateRepo.imagePullSecrets is required for private repo" }}
      imagePullSecrets:
        {{- toYaml $secret | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository | default "ojha931/stress-ng-web"}}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $port := 3000 }}
          ports:
            - name: "stress-ng-web"
              containerPort: {{ $port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ $port }}
          readinessProbe:
            httpGet:
              path: / 
              port: {{ $port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/jobs
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "stress-ng-web.fullname" . }}
