{{- with .Values.image.privateRepo }}
{{- if and .enabled .generateSecret }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "stress-ng-web.name" $ }}-registry-key
  labels:
    {{- include "stress-ng-web.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "stress-ng-web.imagePullSecret" $ }}
{{- end }}
{{- end }}
