apiVersion: v1
kind: Service
metadata:
  name: {{ include "stress-ng-web.fullname" . }}
  labels:
    {{- include "stress-ng-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: "stress-ng-web"
      name: "stress-ng-http-svc"
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{-  end }}
  selector:
    {{- include "stress-ng-web.selectorLabels" . | nindent 4 }}
